mod: defn*

defn: fn_defn
  | fn_decl
  | var_defn
  | struct_defn
  | impl_defn
  | import

fn_defn: access _fn_prototype block_expr
_fn_prototype: "fn" ident "(" param_list ")" [typ]
!access: ["pub"]
param_list: _param_list?
_param_list: receiver ("," param)* ","?
    | param ("," param)* ","?
receiver: "*" mut "self"
param: ident ":" typ

fn_decl: "extern" _fn_prototype ";"

var_defn: access let_stmt

struct_defn: access "struct" ident "{" struct_field_defn_list "}"
struct_field_defn_list: _struct_field_defn_list?
_struct_field_defn_list: struct_field_defn ("," struct_field_defn)* ","?
struct_field_defn: access mut ident ":" typ

impl_defn: "impl" typ "{" fn_defn* "}"

import: "import" ident ";"

?typ: basic_typ
  | ptr_typ
  | array_typ

basic_typ: path
ptr_typ: "*" mut typ
array_typ: "[" typ ";" array_length "]"
array_length: NONNEG_INT

stmt: expr_stmt
  | ret_stmt
  | let_stmt
  | assignment_stmt

expr_stmt: expr ";"
ret_stmt: "return" [expr] ";"
let_stmt: "let" mut ident [":" typ] "=" expr ";"
!mut: ["mut"]

assignment_stmt: place "=" expr ";"

?place: var_expr
  | array_access_expr
  | struct_access_expr
  | deref_expr

?expr: block_expr
  | if_expr
  | while_expr
  | cmp_expr

block_expr: "{" stmt* expr? "}"

if_expr: "if" "(" expr ")" block_expr ("else" block_expr)?

while_expr: "while" "(" expr ")" block_expr

# No recursion in cmp_expr: comparisons can't be chained
?cmp_expr: arith_expr cmp_op arith_expr
  | arith_expr

!cmp_op: "<" | "<=" | "==" | "!=" | ">=" | ">"

?arith_expr: arith_expr add_op term
  | term

!add_op: "+"|"-"

?term: term mul_op factor
  | factor

!mul_op: "*"|"/"

?factor: unary_op factor
  | atom_expr

!unary_op: "&" | "-"

?atom_expr: call_expr
  | array_access_expr
  | struct_expr
  | struct_access_expr
  | deref_expr
  | atom

call_expr: atom_expr "(" arg_list ")"
arg_list: _arg_list?
_arg_list: expr ("," expr)* ","?

array_access_expr: atom_expr "[" expr "]"

struct_expr: basic_typ "{" struct_field_expr_list "}"
struct_field_expr_list: _struct_field_expr_list?
_struct_field_expr_list: struct_field_expr ("," struct_field_expr)* ","?
struct_field_expr: ident ":" expr

struct_access_expr: atom_expr "." ident

deref_expr: atom_expr ".*"

?atom: str_lit
  | int_lit
  | bool_lit
  | var_expr
  | array_expr
  | "(" expr ")"

str_lit: STR_LIT
int_lit: INT_LIT
!bool_lit: "true" | "false"
var_expr: path
path: ident ("::" ident)*
ident: IDENT
array_expr: "[" arg_list "]"

INT_LIT: NONNEG_INT (("i"|"u") (POS_INT | "size"))?
NONNEG_INT: POS_INT | "0"
POS_INT: "1".."9" ("0".."9")*

IDENT: /[_a-zA-Z][_0-9a-zA-Z]*/

%import common.ESCAPED_STRING -> STR_LIT
%import common.WS
%ignore WS
