[project]
name = "leech"
version = "0.0.1"
description = "Leech compiler"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "lark[interegular]>=1.3.1",
    "llvmlite>=0.47.0",
    "more-itertools>=11.1.0",
    "networkx[default]>=3.6.1",
    "rich>=15.0.0",
]

[project.scripts]
leech = "leech:main"

[build-system]
requires = ["uv_build>=0.11.13,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "coverage>=7.14.0",
    "pytest>=9.0.3",
]

[tool.basedpyright]
typeCheckingMode = "basic"

[tool.pytest.ini_options]
xfail_strict = true
