mod: defn*

defn: fn_defn
  | fn_decl
  | var_defn
  | struct_defn
  | trait_defn
  | impl_defn
  | import

fn_defn: access "fn" ident [generic_params] "(" param_list ")" [typ] block_expr
_fn_prototype: "fn" ident "(" param_list ")" [typ]
!access: ["pub"]
param_list: _param_list?
_param_list: receiver ("," param)* ","?
    | param ("," param)* ","?
receiver: "*" mut "self"
param: ident ":" typ

fn_decl: "extern" _fn_prototype ";"

var_defn: access let_stmt

struct_defn: access "struct" ident [generic_params] "{" struct_field_defn_list "}"
struct_field_defn_list: _struct_field_defn_list?
_struct_field_defn_list: struct_field_defn ("," struct_field_defn)* ","?
struct_field_defn: access mut ident ":" typ

trait_defn: access "trait" ident [generic_params] "{" trait_fn* "}"
trait_fn: _fn_prototype ";"

impl_defn: "impl" [generic_params] typ ["for" typ] "{" fn_defn* "}"

import: "import" ident ";"

generic_params: "[" _generic_param_list "]"
_generic_param_list: generic_param ("," generic_param)* ","?
generic_param: ident (":" bound_list)?
bound_list: path ("+" path)*

generic_args: "[" _generic_arg_list "]"
_generic_arg_list: typ ("," typ)* ","?

?typ: basic_typ
  | ptr_typ
  | array_typ

basic_typ: path [generic_args]
ptr_typ: "*" mut typ
array_typ: "[" typ ";" array_length "]"
array_length: NONNEG_INT

stmt: expr_stmt
  | ret_stmt
  | let_stmt
  | assignment_stmt
  | break_stmt
  | continue_stmt

expr_stmt: expr ";"
ret_stmt: "return" [expr] ";"
break_stmt: "break" [ident] ";"
continue_stmt: "continue" [ident] ";"
let_stmt: "let" mut ident [":" typ] "=" expr ";"
!mut: ["mut"]

assignment_stmt: place "=" expr ";"

?place: var_expr
  | array_access_expr
  | struct_access_expr
  | deref_expr

?expr: block_expr
  | if_expr
  | while_expr
  | or_expr

block_expr: "{" stmt* expr? "}"

if_expr: "if" "(" expr ")" block_expr ("else" block_expr)?

while_expr: [ident ":"] "while" "(" expr ")" block_expr

?or_expr: or_expr or_op and_expr
  | and_expr

!or_op: "or"

?and_expr: and_expr and_op not_expr
  | not_expr

!and_op: "and"

?not_expr: not_op not_expr
  | cmp_expr

!not_op: "not"

# No recursion in cmp_expr: comparisons can't be chained
?cmp_expr: arith_expr cmp_op arith_expr
  | arith_expr

!cmp_op: "<" | "<=" | "==" | "!=" | ">=" | ">"

?arith_expr: arith_expr add_op term
  | term

!add_op: "+"|"-"

?term: term mul_op factor
  | factor

!mul_op: "*"|"/"

?factor: unary_op factor
  | atom_expr

!unary_op: "&" | "-"

?atom_expr: call_expr
  | array_access_expr
  | struct_expr
  | struct_access_expr
  | deref_expr
  | atom

call_expr: atom_expr "(" arg_list ")"
arg_list: _arg_list?
_arg_list: expr ("," expr)* ","?

array_access_expr: atom_expr ".[" expr "]"

struct_expr: basic_typ "{" struct_field_expr_list "}"
struct_field_expr_list: _struct_field_expr_list?
_struct_field_expr_list: struct_field_expr ("," struct_field_expr)* ","?
struct_field_expr: ident ":" expr

struct_access_expr: atom_expr "." ident

deref_expr: atom_expr ".*"

?atom: str_lit
  | int_lit
  | bool_lit
  | var_expr
  | array_expr
  | "(" expr ")"

str_lit: STR_LIT
int_lit: INT_LIT
!bool_lit: "true" | "false"
var_expr: path [generic_args]
path: ident ("::" ident)*
ident: IDENT
array_expr: "[" arg_list "]"

INT_LIT: NONNEG_INT (("i"|"u") (POS_INT | "size"))?
NONNEG_INT: POS_INT | "0"
POS_INT: "1".."9" ("0".."9")*

IDENT: /[_a-zA-Z][_0-9a-zA-Z]*/

%import common.ESCAPED_STRING -> STR_LIT
%import common.WS
%ignore WS

COMMENT: /\/\/[^\n]*/
%ignore COMMENT
